// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../js/app/controllers.js", [], []);
goog.addDependency("../../../../js/app/app.js", [], []);
goog.addDependency("../../../../js/app/services.js", [], []);
goog.addDependency("../../../../js/app/common.js", ['autoService.common'], ['goog.dom', 'goog.net.XhrIo', 'goog.events', 'goog.object', 'goog.ui.decorate', 'goog.ui.Container', 'goog.ui.Control', 'goog.style']);
goog.addDependency("../../../../js/app/auction.js", ['autoService.auction'], ['goog.dom', 'goog.net.XhrIo', 'goog.events', 'goog.object', 'goog.ui.decorate', 'goog.ui.Container', 'goog.ui.Control', 'goog.style', 'goog.ui.Dialog', 'goog.json']);
goog.addDependency("../../../../js/app/catalog.js", ['autoService.catalog'], ['goog.dom', 'goog.net.XhrIo', 'goog.ui.AnimatedZippy', 'goog.ui.Zippy', 'goog.ui.ZippyEvent', 'goog.events', 'goog.object', 'goog.array', 'goog.ui.decorate', 'goog.ui.Container', 'goog.ui.Control', 'goog.style', 'goog.ui.Dialog']);
goog.addDependency("../../../../js/app/bids.js", ['autoService.bids'], ['goog.dom', 'goog.net.XhrIo', 'goog.events', 'goog.object', 'goog.ui.decorate', 'goog.ui.Container', 'goog.ui.Control', 'goog.style', 'goog.fx', 'goog.fx.dom', 'goog.fx.AnimationQueue', 'goog.fx.AnimationSerialQueue', 'goog.fx.AnimationParallelQueue']);
goog.addDependency("../../../../js/app/test/auction_test.js", [], ['autoService.auction', 'goog.testing.jsunit', 'goog.testing.ContinuationTestCase', 'goog.testing.jsunit', 'goog.dom', 'goog.dom.NodeType']);
