// This file was autogenerated by calcdeps.py
goog.addDependency("../../../closure-templates/javascript/soyutils.js", [], []);
goog.addDependency("../../../closure-templates/javascript/soyutils_usegoog.js", ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJs', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri', 'soydata.VERY_UNSAFE'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.soy.data.SanitizedContentKind', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../../../closure-templates/javascript/examples/simple_generated_en.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/features_generated_x-zz.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/simple-usage.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/features_generated_en.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/simple_generated_x-zz.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/simple_generated.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/features-usage.js", [], []);
goog.addDependency("../../../../js/app/soy/hello.soy.js", ['autoService.templates'], ['soy', 'soydata']);
goog.addDependency("../../../../js/app/auction.js", ['autoService.auction'], ['goog.dom', 'goog.net.XhrIo', 'goog.events', 'goog.object', 'goog.ui.decorate', 'goog.ui.Container', 'goog.ui.Control', 'goog.style', 'goog.ui.Dialog', 'goog.json']);
goog.addDependency("../../../../js/app/bids.js", ['autoService.bids'], ['goog.dom', 'goog.net.XhrIo', 'goog.events', 'goog.object', 'goog.ui.decorate', 'goog.ui.Container', 'goog.ui.Control', 'goog.style', 'goog.fx', 'goog.fx.dom', 'goog.fx.AnimationQueue', 'goog.fx.AnimationSerialQueue', 'goog.fx.AnimationParallelQueue']);
goog.addDependency("../../../../js/app/catalog.js", ['autoService.catalog'], ['goog.dom', 'goog.net.XhrIo', 'goog.ui.AnimatedZippy', 'goog.ui.Zippy', 'goog.ui.ZippyEvent', 'goog.events', 'goog.object', 'goog.array', 'goog.ui.decorate', 'goog.ui.Container', 'goog.ui.Control', 'goog.style', 'goog.ui.Dialog', 'autoService.templates']);
goog.addDependency("../../../../js/app/common.js", ['autoService.common'], ['goog.dom', 'goog.net.XhrIo', 'goog.events', 'goog.object', 'goog.ui.decorate', 'goog.ui.Container', 'goog.ui.Control', 'goog.style']);
